site_name: Internal Docs Template

theme:
  name: material

nav:
  - Index: index.md
  - Chapter 1:
    - Section 1: chapter1/section1.md
    - Section 2: chapter1/section2.md
  - Chapter 2:
    - Section 1: chapter2/section1.md
    - Section 2: chapter2/section2.md
  - Admin: admin.md


plugins:
  - with-pdf
  - search:
      lang: ja

markdown_extensions:
  - admonition
