name: GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - name: Google Auth
      #   id: auth
      # - uses: 'google-github-actions/auth@v2'
      #   with:
      #     project_id: 'my-project'
      #     workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'

      # - name: Login to GAR
      #   uses: docker/login-action@v3
      #   with:
      #     registry: us-central1-docker.pkg.dev
      #     username: oauth2accesstoken
      #     password: ${{ steps.auth.outputs.access_token }}

      - name: Build Docker image
        run: make docker-build CONFIG=config.mk

      # - name: Push Docker image
      #   run: make docker-push CONFIG=config.mk

      # - name: Deploy to Cloud Run
      #   run: make cloud-run CONFIG=config.mk
